// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://www.google.com/search?q=google+translate&rlz=1C1GCEU_enUS973US973&oq=google+&aqs=chrome.0.69i59l2j69i57j69i60l3j69i65l2.2256j0j9&sourceid=chrome&ie=UTF-8");
    driver.manage().window().setSize(new Dimension(1455, 846));
    driver.findElement(By.id("tw-source-text-ta")).click();
    driver.findElement(By.id("tw-source-text-ta")).sendKeys("Hello");
    driver.findElement(By.id("tw-tl")).click();
    driver.findElement(By.id("tl_list-search-box")).sendKeys("ma");
    driver.findElement(By.cssSelector(".language_list_tl_list > .tw-lliw:nth-child(65)")).click();
  }
}
